import find_tf_idf_10

first_string = [
    "sport includes all forms of competitive physical activity or games which,[1] through casual or organized participation, at least in part aim to use, maintain or improve physical ability and skills while providing enjoyment to participants, and in some cases, entertainment for spectators.[2] Sports can bring positive results to one's physical health. Hundreds of sports exist, from those between single contestants, through to those with hundreds of simultaneous participants, either in teams or competing as individuals. In certain sports such as racing, many contestants may compete, simultaneously or consecutively, with one winner; ",
    "sport"]

second_string = [
    "in others, the ball contest (a match) is between two sides, each attempting to exceed the other. Some sports allow a tie or draw, in which there is no single winner; others provide tie-breaking methods to ensure one winner and one loser. A number of contests may be arranged in a tournament producing a champion. Many sports leagues make an annual champion by arranging games in a regular sports season, followed in some cases by playoffs.",
    "sport"]

third_string = [
    "sport is generally ball recognised as system of activities which are based in physical athleticism or physical dexterity, with the largest major competitions such as the Olympic Games admitting only sports meeting this definition,[3] and other organisations such as the Council of Europe using definitions precluding activities without a physical element from classification as sports.[2] However, a number of competitive, but non-physical, activities claim recognition as mind sports. The International Olympic ",
    "sport"]

six_string = [
    "medicine is the science and practice of establishing the diagnosis, prognosis, treatment, and prevention of disease. Medicine encompasses a variety of health care practices evolved to maintain and restore health by the prevention and treatment of illness. Contemporary medicine applies biomedical sciences, biomedical research, genetics, and medical technology to diagnose, treat, and prevent injury and disease, typically through pharmaceuticals or surgery, but also through therapies as diverse as psychotherapy, external splints and traction, medical devices, biologics, and ionizing radiation, amongst others.[1]",
    "medicine"]

seven_string = [
    "medicine has been around for thousands of years, during most of which it was an art (an area of skill and knowledge) frequently having connections to the religious and philosophical beliefs of local culture. For example, a medicine man would apply herbs and say prayers for healing, or an ancient philosopher and physician would apply bloodletting according to the theories of humorism. In recent centuries, since the advent of modern science, most medicine has become a combination of art and science (both basic and applied, under the umbrella of medical science). While stitching technique for sutures is an art learned through practice, the knowledge of what happens at the cellular and molecular level in the tissues being stitched arises through science. ",
    "medicine"]

eight_string = [
    "Prescientific forms of medicine are now known as traditional medicine and folk medicine, though they do not fall within the modern definition of “medicine” which is based in medical science. Traditional medicine and folk medicine remain commonly used with, or instead of, scientific medicine and are thus called alternative medicine (meaning “[something] other than medicine”, from Latin alter, “other”). For example, evidence on the effectiveness of acupuncture is variable and inconsistent for any condition,[2] but is generally safe when done by an appropriately trained practitioner.[3] In contrast, alternative treatments outside the bounds not just of scientific medicine, but also outside the bounds of safety and efficacy are termed quackery. ",
    "medicine"]
# new_string = ["The physical examination is the examination of the patient for medical signs of disease, which are objective and observable, in contrast to symptoms which are volunteered by the patient and not necessarily objectively observable.[12] The healthcare provider uses the senses of sight, hearing, touch, and sometimes smell (e.g., in infection, uremia, diabetic ketoacidosis). Four actions are the basis of physical examination: inspection, palpation (feel), percussion (tap to determine resonance characteristics), and auscultation (listen), generally in that order although auscultation occurs prior to percussion and palpation for abdominal assessments.","medicine"]
# new_string = ["Tel Aviv is governed by the Tel Aviv-Yafo Municipality, headed by Mayor Ron Huldai, and is home to many foreign embassies.[b] It is a global city and is ranked 25th in the Global Financial Centres Index. Tel Aviv has the third- or fourth-largest economy and the largest economy per capita in the Middle East.[6][7] The city has the 31st highest cost of living in the world.[8] Tel Aviv receives over 2.5 million international visitors annually.[9][10] A party capital in the Middle East, it has a lively nightlife and 24-hour culture.[11][12] Tel Aviv has been called The World's Vegan Food Capital, as it possesses the highest per capita population of vegans in the world, with many vegan eateries throughout the city.[13] Tel Aviv is home to Tel Aviv University, the largest university in the country with ", "third"]
# new_string = ["The city was founded in 1909 by the Yishuv (Jewish residents) as a modern housing estate on the outskirts of the ancient port city of Jaffa, then part of the Jerusalem province of Ottoman Syria. It was at first called 'Ahuzat Bayit' (lit.),[14][15] the name of the association which established the neighbourhood, a name changed the following year to 'Tel Aviv'. Its name means , symbolising both ancient legacy and renewal. Other Jewish suburbs of Jaffa established outside Jaffa's Old City even before Tel Aviv, eventually became part of Tel Aviv, the oldest among them being Neve Tzedek (est. 1886).[16]", "third"]
# new_string = ["The physical examination is the examination of the patient for medical signs of disease, which are objective and observable, in contrast to symptoms which are volunteered by the patient and not necessarily objectively observable.[12] The healthcare provider uses the senses of sight, hearing, touch, and sometimes smell (e.g., in infection, uremia, diabetic ketoacidosis). Four actions are the basis of physical examination: inspection, palpation (feel), percussion (tap to determine resonance characteristics), and auscultation (listen), generally in that order although auscultation occurs prior to percussion and palpation for abdominal assessments.","medicine"]
# new_string = ["Tel Aviv is governed by the Tel Aviv-Yafo Municipality, headed by Mayor Ron Huldai, and is home to many foreign embassies.[b] It is a global city and is ranked 25th in the Global Financial Centres Index. Tel Aviv has the third- or fourth-largest economy and the largest economy per capita in the Middle East.[6][7] The city has the 31st highest cost of living in the world.[8] Tel Aviv receives over 2.5 million international visitors annually.[9][10] A party capital in the Middle East, it has a lively nightlife and 24-hour culture.[11][12] Tel Aviv has been called The World's Vegan Food Capital, as it possesses the highest per capita population of vegans in the world, with many vegan eateries throughout the city.[13] Tel Aviv is home to Tel Aviv University, the largest university in the country with ", "third"]
# new_string = ["The city was founded in 1909 by the Yishuv (Jewish residents) as a modern housing estate on the outskirts of the ancient port city of Jaffa, then part of the Jerusalem province of Ottoman Syria. It was at first called 'Ahuzat Bayit' (lit.),[14][15] the name of the association which established the neighbourhood, a name changed the following year to 'Tel Aviv'. Its name means , symbolising both ancient legacy and renewal. Other Jewish suburbs of Jaffa established outside Jaffa's Old City even before Tel Aviv, eventually became part of Tel Aviv, the oldest among them being Neve Tzedek (est. 1886).[16]", "third"]
# new_string = ["many beds for intensive care and additional beds for patients who need long-term care. Specialized hospitals include trauma centers, rehabilitation hospitals, children's hospitals, seniors' (geriatric) hospitals, and hospitals for dealing with specific medical needs such as psychiatric treatment (see psychiatric hospital) and certain disease categories. Specialized hospitals can help reduce health care costs compared to general hospitals.[2] Hospitals are classified as general, specialty, or government depending on the sources of income ", "medicine"]
# new_string = ["Players advance the ball by bouncing it while walking or running (dribbling) or by passing it to a teammate, both of which require considerable skill. On offense, players may use a variety of shots—the lay-up, the jump shot, or a dunk; on defense, they may steal the ball from a dribbler, intercept passes, or block shots; either offense or defense may collect a rebound, that is, a missed shot that bounces from rim or backboard. It is a violation to lift or drag one's pivot foot without dribbling the ball, to carry it, or to hold the ball with both hands then resume dribbling. ", "third"]
# new_string = ["There are a number of references to traditional, ancient, or prehistoric ball games played in many different parts of the world.[3][4][5] Contemporary codes of football can be traced back to the codification of these games at English public schools during the 19th century.[6][7] The expansion of the British Empire allowed these rules of football to spread to areas of British influence outside the directly controlled Empire.[8] By the end of the 19th century, distinct regional codes were already developing: Gaelic football, for example, deliberately incorporated ", "third"]
# new_string = ["historians as Marn Grook (Djab Wurrung for game ball). The earliest historical account is an anecdote from the 1878 book by Robert Brough-Smyth, The Aborigines of Victoria, in which a man called Richard Thomas is quoted as saying, in about 1841 in Victoria, Australia, that he had witnessed Aboriginal people playing the game: Mr Thomas describes how the foremost player will drop kick a ball made from the skin of a possum and how other players leap into the air in order to catch it. Some historians have theorised that Marn Grook was one of the origins of Australian rules football.", "third"]
#
new_string = [
    "sport is usually governed by a set of rules or customs, which serve to ensure fair competition, and allow consistent adjudication of the winner. Winning can be determined by physical events such as scoring goals or crossing a line first. It can also be determined by judges who are scoring elements of the sporting performance, including objective or subjective measures such as technical performance or artistic impression. ",
    "sport"]



list_of_all_documents = [first_string, second_string, third_string, six_string, seven_string, eight_string]

print(find_tf_idf_10.finds_list_of_all_documents_terms_values(list_of_all_documents))
# print(find_tf_idf_7.finds_list_of_all_documents_terms_values(list_of_all_documents))
find_tf_idf_10.finding_label_of_new_file(new_string,list_of_all_documents)